baseURL = 'https://esacteksab.com/'
languageCode = 'en-us'
title = 'esacteksab'
theme = 'simpl'

[[menus.main]]

[markup]
[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
noClasses = false
wrapperClass = 'highlight not-prose'

[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 1


[params.Author]
github = 'esacteksab'
gitlab = 'esacteksab'
name = 'esacteksab'
