baseURL = 'https://esacteksab.com/'
languageCode = 'en-us'
title = 'esacteksab'

[[menus.main]]

[params.Author]
github = 'esacteksab'
gitlab = 'esacteksab'
name = 'esacteksab'

[build]
_merge = 'deep'

[markup]
_merge = 'deep'

[module]
[[module.imports]]
path = "github.com/esacteksab/simpl"
